apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-k3yi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftim-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-k3yi@sha256:0343eaa881369a342b8f7dc57c41867473cb407e98f0ea81adcf7dfd47ea7e9f
        name: my-nodejs
        resources: {}
status: {}
